name: SSH Connect

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with debugging enabled'
        required: false
        default: false

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"

    - name: Relay SSH
#      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        wget https://raw.githubusercontent.com/WLWolf5/new/master/frp/shadow
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo cp -f shadow /etc/shadow
        rm -rf shadow
        
    - name: Run Frp
#      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      run: |
        mkdir frp && cd frp
        wget https://raw.githubusercontent.com/WLWolf5/new/master/frp/frpc
        wget https://raw.githubusercontent.com/WLWolf5/new/master/frp/frpc.ini
        chmod +x frpc
        ./frpc -c frpc.ini
