name: xxt Gua Wang Ke

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with debugging enabled'
        required: false
        default: false

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"

    - name: Start AFK
      run: |
        git clone --depth=1 https://github.com/Samueli924/chaoxing
        cd chaoxing
        pip install -r requirements.txt
        python main.py -u 18370615006 -p qq110826778 -l 239816174 -s 2
        
